# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "779d507932bb39553636fa296430555b"
name = "Clone Pages"
handle = "clone-pages-12"
application_url = "https://shopify-clone-pages.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true


[webhooks]
api_version = "2025-07" 

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_content,write_online_store_pages"
  
[auth]
redirect_urls = ["https://shopify-clone-pages.vercel.app/auth/callback", "https://shopify-clone-pages.vercel.app/auth/shopify/callback", "https://shopify-clone-pages.vercel.app/api/auth/callback"]

[pos]
embedded = false

# [app_proxy]
# url = "https://shopify-clone-pages.vercel.app/proxy"
# subpath = "preview"
# prefix = "a"
